### ISSUE TITLE
Flagging for stealing

### ISSUE THREAD

**Issue by arifszn** [Akiekano/akiekano.#1]
Fork the repo rather than reuploading it as a brand new project to support the original author. Go through the [Please Read](https://github.com/arifszn/ezprofile#-please-read) section of the original repo.

Your footer says `Made with Akiekano and ❤️`. How can it be made by you if you just changed the config's value?

**Comment by ammarfaizi2** [comment]
Shame on you @Akiekano. You re-uploaded someone's source code and claim it is yours? Seriously WTF! Please respect the open source license. I feel so disgusted with your behavior lately.

**Comment by ammarfaizi2** [comment]
@arifszn I am sorry for this happening to you. You might've seen `@gnuweeb.org` email address on @Akiekano's profile, but in GNU/Weeb I really enforce to respect everyone's copyright. We even put SPDX license identifier and copyright owner in for each file that has owner in our project.

I will make sure we will get this sorted as soon as possible.

And it seems this repo has been forked by someone's else, let me ping him to make sure he stop the copyright violation as well.

Cc: @anandadwipra

Ananda, please delete your fork that's based on this repo (https://github.com/anandadwipra/anandadwipra.github.io). If you want to use the source code, please follow the guidelines and the open source license from the original source, ok?

**Comment by Akiekano** [comment]
Forgive me, yesterday I tried to just present it to my friends about your website, but completely I still say that it comes from your repository. Forgive my mistakes.

**Comment by Akiekano** [comment]
I've fixed it, you can see https://github.com/Akiekano/akiekano.github.io, is this problem solved?

**Comment by anandadwipra** [comment]
Sorry @ammarfaizi2 , @arifszn , I didn't know about this. I will fix it now. I will follow the guide and open source license from the original source

**Comment by ammarfaizi2** [comment]
OK, it seems all of this is a honest mistake. And now we've fixed it. Do you have other concerns @arifszn?

**Comment by arifszn** [comment]
Looks ok now. Thanks for understanding and fixing.
